//=========================================================================
//
//  This skeleton was generated by Mouse 1.6.1 at 2014-12-01 21:27:05 GMT
//  from grammar
//    '/home/celer/Project/gomouse/examples/examples2/myGrammar.txt'.
//
//=========================================================================

package main;

import "fmt"
import mouse "../../src/runtime";

type MySemantics struct {
	result int;  
	mouse.SemanticsBase
}
func NewMySemantics() *MySemantics{
  s:=MySemantics{}
  return &s;
}
//---------------------------------------------------------------------
//  Sum = Number ("+" Number)* !_
//---------------------------------------------------------------------
func (this *MySemantics) sum() {
      s:=0;
      for i:=0;i<this.RHSSize();i+=2 {
        r,ok:=this.RHS(i).Get().(int);
				if(ok){
					s+=r;
				}
			}
			this.result=s;
}

//---------------------------------------------------------------------
//  Number = [0-9]+
//---------------------------------------------------------------------
func (this *MySemantics) number() {
	var i int;
	fmt.Sscanf(this.LHS().Text(),"%d",&i);
	this.LHS().Put(i);
}

